[project]
name = "world-stage"
version = "1.0.8"
description = "Voting website for World Stage."
requires-python = ">= 3.9"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"