[project]
name = "world-stage"
version = "1.7.14"
description = "Voting website for World Stage."
requires-python = ">= 3.9"
dependencies = [
    "flask",
    "markdown-it-py"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"